# Generated by Django 4.1 on 2022-08-07 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255, verbose_name='region')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('place_src', models.CharField(max_length=255, verbose_name='place_src')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info_type', models.CharField(choices=[('main', 'main'), ('accreditation', 'accreditation')], default='main', max_length=64, verbose_name='info_type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos',
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'newss',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('service_type', models.CharField(choices=[('testing', 'testing'), ('certification', 'certification')], default='testing', max_length=64, verbose_name='service_type')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('image_document', models.ImageField(upload_to='images/', verbose_name='image_document')),
                ('requirements', models.TextField(verbose_name='requirements')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255, verbose_name='contact_name')),
                ('phone', models.CharField(max_length=255, verbose_name='contact_name')),
                ('email', models.CharField(max_length=255, verbose_name='contact_name')),
                ('comment', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='csd.contact')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csd.service')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.AddConstraint(
            model_name='info',
            constraint=models.UniqueConstraint(fields=('info_type',), name='info_type_idx'),
        ),
    ]
